version: "3.9"

services:
  web:
    build: .
    ports:
      - "9000:9000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tasks_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
